#!/bin/bash

# setup
apt install -y wget
rm -f /etc/apt/sources.list.d/*
echo 'deb http://kali.download/kali kali-rolling main non-free contrib' > /etc/apt/sources.list
wget https://archive.kali.org/archive-key.asc -O /etc/apt/trusted.gpg.d/kali-archive-keyring.asc

# convert to kali
apt update
apt -y upgrade
apt -y install kali-defaults
apt -y install kali-linux-headless
apt -y install nuclei

# install docker
apt -y purge docker.io docker-doc docker-compose podman-docker containerd runc
apt -y install ca-certificates curl gnupg
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
chmod a+r /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  bullseye stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null
apt update
apt -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# reboot
echo "Reboot now? (y/n)"
read -r answer
if [ "$answer" != "${answer#[Yy]}" ] ;then
    reboot
fi
